---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: a-writer-read
  namespace: project-a
subjects:
- kind: ServiceAccount
  name: writer
  namespace: project-a
roleRef:
  kind: Role
  name: pod-write
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: a-writer-write
  namespace: project-a
subjects:
- kind: ServiceAccount
  name: writer
  namespace: project-a
roleRef:
  kind: Role
  name: pod-read
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: a-reader-read
  namespace: project-a
subjects:
- kind: ServiceAccount
  name: reader
  namespace: project-a
roleRef:
  kind: Role
  name: pod-read
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: a-writer-read
  namespace: project-b
subjects:
- kind: ServiceAccount
  name: writer
  namespace: project-a
roleRef:
  kind: Role
  name: pod-read
  apiGroup: rbac.authorization.k8s.io
